// example/svelte/page/component/SharedCounterIsland.svelte
<script lang="ts">
    import { Island } from "../../../../runtime/svelte.client.ts";
    import SharedCounter from "./SharedCounter.svelte";
    import { NAME } from "./SharedCounterIsland.script.ts";

    const props = $$props
</script>

<Island name={NAME} component={SharedCounter} {props}>
    <slot />
</Island>

// example/solidjs/page/component/counter/SharedCounterIsland.tsx
/* @jsxRuntime automatic */
/* @jsxImportSource solid-js */
import { Island } from "../../../../../runtime/solidjs.client.ts";
import { NAME } from "./SharedCounterIsland.script.ts";
import { SharedCounter, SharedCounterProps } from "./SharedCounter.tsx";

export function SharedCounterIsland(props: SharedCounterProps) {
    return <Island name={NAME} Component={SharedCounter} props={props} />;
}
