// packages/frugal_preact/Island.tsx
/* @jsx preact.h */
/* @jsxFrag preact.Fragment */
import * as preact from 'preact';
import { cx } from '../loader_style/styled.ts';

import type { HydrationStrategy } from './types.ts';

export type IslandProps<PROPS> = {
    className?: string;
    strategy?: HydrationStrategy;
    clientOnly?: boolean;
    query?: string;
    name: string;
    Component: preact.ComponentType<PROPS>;
    props: PROPS;
};

export function Island<PROPS>(
    { className, name, clientOnly = false, Component, props, ...rest }:
        IslandProps<
            PROPS
        >,
) {
    if (typeof document === 'undefined') {
        return (
            <div
                className={cx(`host-${name}`, className)}
                data-hydratable={name}
                data-hydration-strategy={rest.strategy ?? 'load'}
                data-hydration-query={rest.query}
            >
                <script
                    type='application/json'
                    dangerouslySetInnerHTML={{ __html: JSON.stringify(props) }}
                />
                {!clientOnly && <Component {...props} />}
            </div>
        );
    }

    return <Component {...props} />;
}

// runtime/svelte/Island.svelte
<script>
    import {
        START_NO_DIFF_COMMENT,
        END_NO_DIFF_COMMENT,
    } from "../../src/runtime/client_session/render/constant.ts";

    export let name;
    export let component;
    export let props;
    export let strategy = "load";
    export let query;
</script>

{@html `<!--${START_NO_DIFF_COMMENT}-->`}

<div
    data-hydratable={name}
    data-hydration-strategy={strategy}
    data-hydration-query={query}
>
    {@html `<script type="application/json">${JSON.stringify({
        props,
    })}</script>`}
    <svelte:component this={component} {...props}><slot /></svelte:component>
    <div data-svelte-slot>
        <slot />
    </div>
</div>
{@html `<!--${END_NO_DIFF_COMMENT}-->`}

<style>
    [data-svelte-slot] {
        display: none;
    }
</style>
