// example/svelte/page/page1/Page1.svelte
<script>
	import SharedCounterIsland from "../component/SharedCounterIsland.svelte";

	export let assets;
	const styles = assets.get('style');
	const scripts = assets.get("script");
</script>

<svelte:head>
	{#each scripts as src}
		<script type="module" src={src}></script>
	{/each}
</svelte:head>

<span>Page 1</span>
<div style="border:1px solid black;">
	<SharedCounterIsland page="page 1" />
</div>
<a href="/page2">page 2</a>

// example/preact/Page1.tsx
import { Head, PageProps } from "../../runtime/preact.server.ts";
import { Island1Island } from "./island1.island.tsx";
import "./session.script.ts";

export function Page1(props: PageProps) {
    const scriptSrc = props.assets["script"][props.descriptor];
    return (
        <div>
            <Head>
                {scriptSrc && <script type="module" src={scriptSrc} />}
            </Head>
            <span>Page 1</span>
            <Island1Island />
            <a href="/page2">page 2</a>
        </div>
    );
}
