// src/runtime/preact/getRenderFrom.tsx
/* @jsxRuntime automatic */
/* @jsxImportSource preact */
import * as server from "preact-render-to-string";
import { HeadProvider } from "./Head.tsx";
import * as descriptor from "../../page/PageDescriptor.ts";
import { JSONValue } from "../../page/JSONValue.ts";
import { DataProvider } from "./dataContext.tsx";

export type PageProps = {
    descriptor: string;
    assets: descriptor.Assets;
};

export type Page = preact.ComponentType<PageProps>;

export type DocumentProps = {
    head: preact.VNode[];
    descriptor: string;
    assets: descriptor.Assets;
    dangerouslySetInnerHTML: { __html: string };
};

export type Document = preact.ComponentType<DocumentProps>;

type ContentConfig = {
    Document: Document;
    embedData: boolean;
};

const DEFAULT_DOCUMENT: Document = (
    { head, dangerouslySetInnerHTML }: DocumentProps,
) => {
    const htmlIndex = head.findIndex((node) => node.type === "html");

    const htmlProps = {};

    if (htmlIndex !== -1) {
        const [html] = head.splice(htmlIndex, 1);
        Object.assign(htmlProps, html.props);
    }

    return (
        <html {...htmlProps}>
            <head>
                {head}
            </head>
            <body dangerouslySetInnerHTML={dangerouslySetInnerHTML} />
        </html>
    );
};

export function getRenderFrom<PATH extends string, DATA extends JSONValue>(
    Page: Page,
    {
        Document = DEFAULT_DOCUMENT,
        embedData = false,
    }: Partial<ContentConfig> = {},
): descriptor.Render<PATH, DATA> {
    return ({
        data,
        pathname,
        descriptor,
        assets,
    }) => {
        let head: preact.VNode[] = [];

        const html = server.render(
            <HeadProvider
                onHeadUpdate={(nextHead) => {
                    head = nextHead;
                }}
            >
                <DataProvider
                    embedData={embedData}
                    context={{ data, pathname }}
                >
                    <Page
                        descriptor={String(descriptor)}
                        assets={assets}
                    />
                </DataProvider>
            </HeadProvider>,
        );

        return `<!DOCTYPE html>${
            server.render(
                <Document
                    descriptor={String(descriptor)}
                    assets={assets}
                    head={head}
                    dangerouslySetInnerHTML={{ __html: html }}
                />,
            )
        }`;
    };
}

// src/runtime/solidjs/getRenderFrom.tsx
/* @jsxRuntime automatic */
/* @jsxImportSource solid-js */
import { NoHydration, render, renderToString } from "solid-js/web";
import * as solid from "solid-js";
import { MetaProvider, renderTags } from "@solidjs/meta";
import * as descriptor from "../../page/PageDescriptor.ts";
import { JSONValue } from "../../page/JSONValue.ts";
import { DataProvider } from "./dataContext.tsx";
import { Assets } from "../../page/Assets.ts";

export type PageProps = {
    descriptor: string;
    assets: Assets;
};

export type Page = solid.Component<PageProps>;

export type DocumentProps = {
    tags: any[];
    descriptor: string;
    assets: Assets;
    innerHTML: string;
};

export type Document = solid.Component<DocumentProps>;

type RenderConfig = {
    Document?: Document;
    embedData?: boolean;
};

const DEFAULT_DOCUMENT: Document = (
    { tags, innerHTML }: DocumentProps,
) => {
    return (
        <html>
            <head innerHTML={renderTags(tags)} />
            <body innerHTML={innerHTML} />
        </html>
    );
};

export function getRenderFrom<PATH extends string, DATA extends JSONValue>(
    Page: Page,
    {
        Document = DEFAULT_DOCUMENT,
        embedData = false,
    }: RenderConfig = {},
): descriptor.Render<PATH, DATA> {
    return ({
        data,
        pathname,
        descriptor,
        assets,
    }) => {
        const tags: any[] = [];

        const html = renderToString(() => (
            <NoHydration>
                <MetaProvider tags={tags}>
                    <DataProvider context={{ data, embedData, pathname }}>
                        <Page
                            descriptor={descriptor}
                            assets={assets}
                        />
                    </DataProvider>
                </MetaProvider>
            </NoHydration>
        ));

        return `<!DOCTYPE html>${
            renderToString(() => (
                <Document
                    descriptor={descriptor}
                    assets={assets}
                    tags={tags}
                    innerHTML={html}
                />
            ))
        }`;
    };
}
