// exemples/preact/Counter.tsx
/* @jsxRuntime automatic */
/* @jsxImportSource preact */
import * as hooks from 'preact/hooks';
import * as signal from 'preact/signals';

export type CounterProps = {
    title: string;
};

const count = new signal.Signal(0);

export function Counter({ title }: CounterProps) {
    return (
        <div>
            <h2>{title}</h2>
            <div>value: {String(count)}</div>
            <button onClick={() => count.value += 1}>Increment</button>
        </div>
    );
}

// exemples/svelte/src/Counter.svelte
<script>
    import { count } from "./store.ts";
    export let title;

    function incrementCount() {
        count.update((count) => count + 1);
    }

    let countValue;

    count.subscribe((value) => {
        countValue = value;
    });
</script>

<div>
    <h2>{title}</h2>
    <div>value: {countValue}</div>
    <button on:click={incrementCount}>Increment</button>
</div>
