// exemples/preact/src/Counter.island.tsx
import { Island, IslandProps } from 'frugal/runtime/preact.client.ts';

import { NAME } from './Counter.script.ts';
import { Counter, CounterProps } from './Counter.tsx';

type CounterIslandProps =
  & CounterProps
  & Pick<IslandProps<unknown>, 'strategy' | 'clientOnly' | 'query'>;

export function CounterIsland(
  { strategy, clientOnly, query, ...props }: CounterIslandProps,
) {
  return (
    <Island
      strategy={strategy}
      clientOnly={clientOnly}
      query={query}
      name={NAME}
      Component={Counter}
      props={props}
    />
  );
}

// exemples/svelte/src/Counter.island.svelte
<script lang="ts">
    import Counter from "./Counter.svelte";
    import Island from "frugal/runtime/svelte/Island.svelte";

    import { NAME } from "./Counter.script.ts";

    let { strategy, clientOnly, query, ...props } = $$props;
</script>

<Island name={NAME} component={Counter} {props} {strategy} {clientOnly} {query}>
    <slot />
</Island>
