// docs/pages/docs/examples/static-refresh/Counter.island.tsx
/* @jsxRuntime automatic */
/* @jsxImportSource preact */
import { Island } from '../../../../dep/frugal/preact.client.ts';

import { NAME } from './Counter.script.ts';
import { Counter as Component } from './Counter.tsx';

export function Counter() {
    return <Island Component={Component} name={NAME} />;
}

// exemples/svelte/src/Counter.island.svelte
<script lang="ts">
    import Counter from "./Counter.svelte";
    import Island from "frugal/runtime/svelte/Island.svelte";

    import { NAME } from "./Counter.script.ts";

    let { strategy, clientOnly, query, ...props } = $$props;
</script>

<Island name={NAME} component={Counter} {props} {strategy} {clientOnly} {query}>
    <slot />
</Island>
