// example/solidjs/page/page1/Page1.tsx
/* @jsxRuntime automatic */
/* @jsxImportSource solid-js */
import { PageProps } from "../../../../runtime/solidjs.server.ts";
import { SharedCounterIsland } from "../component/counter/SharedCounterIsland.tsx";
import "../session.script.ts";

export function Page1(props: PageProps) {
    const scripts = props.assets.get("script");
    return (
        <>
            <div>
                <span>Page 1</span>
                <div style="border:1px solid black;">
                    <SharedCounterIsland page="page 1" />
                </div>
                <a href="/page2">page 2</a>
            </div>
            {scripts.map((src) => {
                return <script type="module" src={src} />;
            })}
        </>
    );
}

// example/svelte/page/page1/Page1.svelte
<script>
	import SharedCounterIsland from "../component/SharedCounterIsland.svelte";

	export let assets;
	const styles = assets.get('style');
	const scripts = assets.get("script");
</script>

<svelte:head>
	{#each scripts as src}
		<script type="module" src={src}></script>
	{/each}
</svelte:head>

<span>Page 1</span>
<div style="border:1px solid black;">
	<SharedCounterIsland page="page 1" />
</div>
<a href="/page2">page 2</a>
